import { test, expect } from '@playwright/test';

test('business workflow, EN/TR switching, persistence, and authoritative order detail', async ({ page }) => {
  const suffix = Date.now(); const email = `business-ui-${suffix}@example.com`;
  await page.goto('/auth/register');
  await page.getByLabel('Full name').fill('Business Reviewer'); await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill('BusinessPassword123!'); await page.getByLabel('Confirm password').fill('BusinessPassword123!');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page).toHaveURL(/\/auth\/login/);
  await page.getByLabel('Email address').fill(email); await page.getByLabel('Password', { exact: true }).fill('BusinessPassword123!'); await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/products$/);
  await page.getByRole('button', { name: 'TR', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Ürünler', exact: true })).toBeVisible();
  for (const name of ['Ürünler', 'Kategoriler', 'Müşteriler', 'Siparişler']) await expect(page.getByRole('navigation').getByRole('link', { name, exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Çıkış', exact: true })).toBeVisible();
  await page.reload(); await expect(page.getByRole('heading', { name: 'Ürünler', exact: true })).toBeVisible();
  expect(await page.evaluate(() => localStorage.getItem('catalog.language'))).toBe('tr');
  await page.getByRole('navigation').getByRole('link', { name: 'Kategoriler', exact: true }).click();
  await page.getByRole('link', { name: 'Yeni kategori', exact: false }).click();
  await page.getByRole('button', { name: 'Kategori oluştur', exact: true }).click();
  await expect(page.getByText('Bir ad girin.', { exact: true })).toBeVisible();
  await page.getByLabel('Ad', { exact: false }).fill(`Office ${suffix}`); await page.getByLabel('Açıklama', { exact: true }).fill('Office essentials');
  await page.getByRole('button', { name: 'Kategori oluştur', exact: true }).click();
  await expect(page.getByRole('heading', { name: `Office ${suffix}`, exact: true })).toBeVisible();
  const categoryId = page.url().split('/').at(-1)!;
  await page.getByRole('link', { name: 'Kategoriyi düzenle', exact: true }).click();
  await page.getByLabel('Ad', { exact: false }).fill(`Office updated ${suffix}`); await page.getByRole('button', { name: 'Değişiklikleri kaydet', exact: true }).click();
  await expect(page.getByRole('heading', { name: `Office updated ${suffix}`, exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Edit category', exact: true })).toBeVisible();
  await page.getByRole('navigation').getByRole('link', { name: 'Products', exact: true }).click(); await page.getByRole('link', { name: 'New product', exact: true }).click();
  await page.getByLabel('Product name').fill(`Paper ${suffix}`); await page.getByLabel('Category', { exact: false }).selectOption(categoryId); await page.getByLabel('Price (USD)').fill('100');
  await page.getByRole('button', { name: 'Create product', exact: true }).click(); await expect(page.getByRole('heading', { name: `Paper ${suffix}`, exact: true })).toBeVisible();
  const firstId = page.url().split('/').at(-1)!;
  await page.getByRole('link', { name: 'Edit product', exact: true }).click(); await page.getByLabel('Price (USD)').fill('100.25'); await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByText('$100.25', { exact: true })).toBeVisible();
  await page.goto('/products/new'); await page.getByLabel('Product name').fill(`Pen ${suffix}`); await page.getByLabel('Category', { exact: false }).selectOption(categoryId); await page.getByLabel('Price (USD)').fill('50'); await page.getByRole('button', { name: 'Create product', exact: true }).click();
  await expect(page.getByRole('heading', { name: `Pen ${suffix}`, exact: true })).toBeVisible(); const secondId = page.url().split('/').at(-1)!;
  await page.getByRole('navigation').getByRole('link', { name: 'Customers', exact: true }).click(); await page.getByRole('link', { name: 'New customer', exact: false }).click();
  await page.getByLabel('Name', { exact: false }).fill(`Acme ${suffix}`); await page.getByLabel('Email', { exact: true }).fill('acme@example.com'); await page.getByLabel('Phone').fill('5551234567'); await page.getByLabel('Address').fill('Istanbul'); await page.getByRole('button', { name: 'Create customer', exact: true }).click();
  await expect(page.getByRole('heading', { name: `Acme ${suffix}`, exact: true })).toBeVisible(); const customerId = page.url().split('/').at(-1)!;
  await page.getByRole('link', { name: 'Edit customer', exact: true }).click(); await page.getByLabel('Phone').fill('5557654321'); await page.getByRole('button', { name: 'Save changes', exact: true }).click(); await expect(page.getByText('5557654321', { exact: true })).toBeVisible();
  await page.getByRole('navigation').getByRole('link', { name: 'Orders', exact: true }).click(); await page.getByRole('link', { name: 'New order', exact: false }).click();
  await page.getByLabel('Customer', { exact: false }).selectOption(customerId); await page.getByLabel('Product name', { exact: false }).nth(0).selectOption(firstId); await page.getByLabel('Quantity', { exact: false }).nth(0).fill('2'); await page.getByRole('button', { name: 'Add item', exact: false }).click();
  await page.getByLabel('Product name', { exact: false }).nth(1).selectOption(secondId); await page.getByLabel('Quantity', { exact: false }).nth(1).fill('3'); await expect(page.locator('.order-total')).toContainText('$350.50');
  await page.getByRole('button', { name: 'Create order', exact: true }).click(); await expect(page.getByRole('heading', { name: /^ORD-/ })).toBeVisible();
  const orderUrl = page.url(); await expect(page.locator('.order-total')).toContainText('$350.50'); await expect(page.getByRole('row').filter({ hasText: `Paper ${suffix}` })).toContainText('$200.50');
  await page.getByRole('button', { name: 'Confirm', exact: true }).click(); await expect(page.locator('.badge')).toHaveText('Confirmed');
  await page.getByRole('button', { name: 'TR', exact: true }).click(); await expect(page.locator('.badge')).toHaveText('Onaylandı'); await expect(page.locator('.order-total')).toContainText('350,50'); await page.getByRole('button', { name: 'Tamamla', exact: true }).click(); await expect(page.locator('.badge')).toHaveText('Tamamlandı');
  await page.reload(); await expect(page.locator('.badge')).toHaveText('Tamamlandı'); await expect(page.getByRole('button', { name: 'Çıkış' })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  if (process.env.CAPTURE_SCREENSHOTS) await page.screenshot({ path: '../.tools/order-detail-tr.png', fullPage: true });
  await page.getByRole('button', { name: 'EN', exact: true }).click(); await page.getByRole('navigation').getByRole('link', { name: 'Orders', exact: true }).click(); await expect(page.getByRole('listitem').filter({ hasText: `Acme ${suffix}` })).toContainText('Completed');
  await page.goto(orderUrl); await expect(page.locator('.order-total')).toContainText('$350.50');
});
