import { promoteRegistered } from './admin-helper';
import { test, expect } from '@playwright/test';

test('registration, authentication, product lifecycle, and protected routes', async ({ page }) => {
  const email = `browser-${Date.now()}@example.com`;
  const password = 'BrowserPassword123!';
  const name = `Browser product ${Date.now()}`;
  await page.goto('/products/new');
  await expect(page).toHaveURL(/\/auth\/login$/);
  await page.getByRole('link', { name: 'Create an account' }).click();
  await page.getByLabel('Full name').fill('Browser User');
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByLabel('Confirm password').fill('different');
  await page.getByRole('button', { name: 'Create account' }).click();
  await expect(page.getByText('Passwords do not match.')).toBeVisible();
  await page.getByLabel('Confirm password').fill(password);
  await page.getByRole('button', { name: 'Create account' }).click();
  await expect(page.getByText('Account created. Sign in to continue.')).toBeVisible();
  await promoteRegistered(page.request, email);
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill('incorrect-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Email or password is incorrect.');
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await page.getByRole('navigation').getByRole('link', { name: 'Products', exact: true }).click();
  const session = await page.evaluate(() => JSON.parse(sessionStorage.getItem('catalog.session')!));
  const apiBase = process.env.API_URL ?? 'http://localhost:5080';
  const categoryResponse = await page.request.post(`${apiBase}/api/categories`, { headers: { Authorization: `Bearer ${session.accessToken}` }, data: { name: `Browser category ${Date.now()}`, description: '', isActive: true } });
  expect(categoryResponse.status()).toBe(201);
  const category = await categoryResponse.json();
  await page.getByRole('link', { name: 'New product', exact: true }).click();
  await page.getByLabel('Category', { exact: false }).selectOption(category.id);
  await page.getByLabel('Product name').fill(name);
  await page.getByLabel('Description').fill('Created from the real browser.');
  await page.getByLabel('Price (USD)').fill('-1');
  await page.getByRole('button', { name: 'Create product', exact: true }).click();
  await expect(page.getByText('Price cannot be negative.')).toBeVisible();
  await page.getByLabel('Price (USD)').fill('0.0000001');
  await page.getByRole('button', { name: 'Create product', exact: true }).click();
  await expect(page.getByText('Use no more than two decimal places.')).toBeVisible();
  await page.getByLabel('Price (USD)').fill('9999999900.03');
  await page.getByRole('button', { name: 'Create product', exact: true }).click();
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
  const detailUrl = page.url();
  await page.reload();
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
  await expect(page.getByText('$9,999,999,900.03')).toBeVisible();
  await page.getByRole('link', { name: 'Edit product', exact: true }).click();
  await expect(page.getByLabel('Product name')).toHaveValue(name);
  await page.getByLabel('Product name').fill(`${name} updated`);
  await page.getByLabel('Price (USD)').fill('40.25');
  await page.getByLabel('Active product').uncheck();
  await page.getByRole('button', { name: 'Save changes' }).click();
  await expect(page.getByRole('heading', { name: `${name} updated`, exact: true })).toBeVisible();
  await expect(page.locator('.badge')).toContainText('Inactive');
  await page.getByRole('link', { name: 'Back to products' }).click();
  const row = page.getByRole('row').filter({ hasText: `${name} updated` });
  await expect(row).toContainText('$40.25');
  if (process.env.CAPTURE_SCREENSHOTS) {
    await page.screenshot({ path: '../.tools/catalog-desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: '../.tools/catalog-mobile.png', fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.setViewportSize({ width: 1280, height: 720 });
  }
  await row.getByRole('button', { name: `Delete ${name} updated`, exact: true }).click();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(row).toBeVisible();
  await row.getByRole('button', { name: `Delete ${name} updated`, exact: true }).click();
  await page.getByRole('button', { name: 'Delete product', exact: true }).click();
  await expect(row).toHaveCount(0);
  expect((await page.request.delete(`${apiBase}/api/categories/${category.id}`, { headers: { Authorization: `Bearer ${session.accessToken}` } })).status()).toBe(204);
  await page.goto(detailUrl);
  await expect(page.getByRole('heading', { name: 'Product not found', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page).toHaveURL(/\/auth\/login$/);
  await page.goto(detailUrl);
  await expect(page).toHaveURL(/\/auth\/login$/);
});

test('expired stored session redirects, mobile auth fits, and network errors display', async ({ page }) => {
  await page.goto('/auth/login');
  await page.evaluate(() => sessionStorage.setItem('catalog.session', JSON.stringify({ accessToken: 'expired', expiresAt: '2000-01-01T00:00:00Z', user: { id: 'expired', name: 'Expired', email: 'expired@example.com', role: 'Admin', isActive: true, createdAt: '2026-10-01T00:00:00Z', updatedAt: null } })));
  await page.goto('/products');
  await expect(page).toHaveURL(/\/auth\/login$/);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.route('**/api/auth/login', route => route.abort());
  await page.getByLabel('Email address').fill('user@example.com');
  await page.getByLabel('Password', { exact: true }).fill('SomePassword123!');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Unable to reach the server.');
});

test('invalid bearer token clears session after a protected API 401', async ({ page }) => {
  await page.goto('/auth/login');
  await page.evaluate(() => sessionStorage.setItem('catalog.session', JSON.stringify({ accessToken: 'invalid-token', expiresAt: new Date(Date.now() + 3600000).toISOString(), user: { id: 'invalid', name: 'Invalid', email: 'invalid@example.com', role: 'Admin', isActive: true, createdAt: '2026-10-01T00:00:00Z', updatedAt: null } })));
  await page.goto('/products');
  await expect(page).toHaveURL(/\/auth\/login$/);
  expect(await page.evaluate(() => sessionStorage.getItem('catalog.session'))).toBeNull();
});
