import { promoteRegistered } from './admin-helper';
import { test, expect } from '@playwright/test';

test('inventory operations, pending shortage, confirmation/cancellation, audit links and TR mobile', async ({ page }) => {
  const base = `${process.env.API_URL ?? 'http://localhost:5080'}/api`;
  const email = `inventory-ui-${Date.now()}@example.com`; const password = 'InventoryBrowser123!';
  expect((await page.request.post(`${base}/auth/register`, { data: { name: 'Inventory Reviewer', email, password } })).status()).toBe(201);
  await promoteRegistered(page.request, email);
  const session = await (await page.request.post(`${base}/auth/login`, { data: { email, password } })).json();
  const headers = { Authorization: `Bearer ${session.accessToken}` };
  const category = await (await page.request.post(`${base}/categories`, { headers, data: { name: `Stock category ${Date.now()}`, description: '', isActive: true } })).json();
  const product = await (await page.request.post(`${base}/products`, { headers, data: { categoryId: category.id, name: `Stock notebook ${Date.now()}`, description: '', price: 12.50, isActive: true } })).json();
  const customer = await (await page.request.post(`${base}/customers`, { headers, data: { name: `Stock customer ${Date.now()}`, email: '', phone: '', address: '', isActive: true } })).json();
  await page.goto('/auth/login'); await page.evaluate(value => sessionStorage.setItem('catalog.session', JSON.stringify(value)), session);
  await page.goto(`/inventory/${product.id}`);
  await expect(page.getByTestId('stock-quantity')).toHaveText('0');
  await expect(page.getByText('Out of stock', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Apply operation', exact: true }).click();
  await expect(page.getByText('Enter a reason.', { exact: true })).toBeVisible();
  await page.getByLabel('Quantity', { exact: true }).fill('10'); await page.getByLabel('Reason', { exact: true }).fill('Opening count');
  await page.getByRole('button', { name: 'Apply operation', exact: true }).click(); await expect(page.getByTestId('stock-quantity')).toHaveText('10');
  await page.getByRole('button', { name: 'Minimum stock level', exact: true }).click();
  await page.getByLabel('Minimum stock level', { exact: true }).fill('-1'); await page.getByRole('button', { name: 'Apply operation', exact: true }).click();
  await expect(page.getByText('Minimum stock level cannot be negative.', { exact: true })).toBeVisible();
  await page.getByLabel('Minimum stock level', { exact: true }).fill('10'); await page.getByRole('button', { name: 'Apply operation', exact: true }).click();
  await expect(page.getByTestId('minimum-level')).toHaveText('10'); await expect(page.getByText('Low stock', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Stock out', exact: true }).click();
  await page.getByLabel('Quantity', { exact: true }).fill('11'); await page.getByLabel('Reason', { exact: true }).fill('Invalid withdrawal');
  await page.getByRole('button', { name: 'Apply operation', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm decrease', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Insufficient stock');
  await expect(page.getByTestId('stock-quantity')).toHaveText('10');
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByLabel('Quantity', { exact: true }).fill('3'); await page.getByLabel('Reason', { exact: true }).fill('Damaged items');
  await page.getByRole('button', { name: 'Apply operation', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm decrease', exact: true }).click();
  await expect(page.getByTestId('stock-quantity')).toHaveText('7');
  await page.getByRole('button', { name: 'Adjust stock', exact: true }).click();
  await page.getByLabel('Quantity', { exact: true }).fill('2'); await page.getByLabel('Reason', { exact: true }).fill('Count correction');
  await page.getByRole('button', { name: 'Apply operation', exact: true }).click(); await expect(page.getByTestId('stock-quantity')).toHaveText('9');
  await page.getByLabel('Direction', { exact: true }).selectOption('Decrease');
  await page.getByLabel('Reason', { exact: true }).fill('Recount');
  await page.getByRole('button', { name: 'Apply operation', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm decrease', exact: true }).click(); await expect(page.getByTestId('stock-quantity')).toHaveText('8');
  await page.goto('/orders/new'); await page.getByLabel('Customer', { exact: false }).selectOption(customer.id);
  await page.getByLabel('Product name', { exact: false }).selectOption(product.id); await page.getByLabel('Quantity', { exact: false }).fill('9');
  await expect(page.getByText('Requested quantity exceeds current stock. Pending orders can still be created.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Create order', exact: true }).click(); await expect(page.getByRole('heading', { name: /^ORD-/ })).toBeVisible();
  const orderUrl = page.url();
  await page.getByRole('button', { name: 'Confirm', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Insufficient stock'); await expect(page.locator('.badge')).toHaveText('Pending');
  await page.goto(`/inventory/${product.id}`); await page.getByLabel('Quantity', { exact: true }).fill('2'); await page.getByLabel('Reason', { exact: true }).fill('Additional supply');
  await page.getByRole('button', { name: 'Apply operation', exact: true }).click(); await expect(page.getByTestId('stock-quantity')).toHaveText('10');
  await page.goto(orderUrl); await page.getByRole('button', { name: 'Confirm', exact: true }).click(); await expect(page.locator('.badge')).toHaveText('Confirmed');
  await page.goto(`/inventory/${product.id}`); await expect(page.getByTestId('stock-quantity')).toHaveText('1');
  await expect(page.getByText('Order deduction', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.goto(orderUrl); await page.getByRole('button', { name: 'Cancel order', exact: true }).click(); await expect(page.locator('.badge')).toHaveText('Cancelled');
  await page.goto(`/inventory/${product.id}`); await expect(page.getByTestId('stock-quantity')).toHaveText('10');
  await expect(page.getByText('Order cancellation return', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.getByRole('button', { name: 'TR', exact: true }).click(); await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('navigation').getByRole('link', { name: 'Stok', exact: true })).toHaveAttribute('aria-current', 'page');
  await expect(page.getByRole('heading', { name: 'Hareket geçmişi', exact: true })).toBeVisible();
  await expect(page.getByText('Sipariş iptal iadesi', { exact: true }).filter({ visible: true })).toBeVisible();
  await page.getByRole('button', { name: 'İşlemi uygula', exact: true }).click();
  await expect(page.getByText('Bir gerekçe girin.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByText('Enter a reason.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'TR', exact: true }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  if (process.env.CAPTURE_SCREENSHOTS) await page.screenshot({ path: '../.tools/phase3/inventory-detail-tr-mobile.png', fullPage: true });
  await page.getByRole('navigation').getByRole('link', { name: 'Stok', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Stok', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('inventory empty/error states and validation translate immediately', async ({ page }) => {
  await page.goto('/auth/login');
  await page.evaluate(() => {
    localStorage.setItem('catalog.language', 'tr');
    sessionStorage.setItem('catalog.session', JSON.stringify({ accessToken: 'inventory-state-fixture', expiresAt: new Date(Date.now() + 3600000).toISOString(), user: { id: 'fixture', name: 'Reviewer', email: 'reviewer@example.com', role: 'Admin', isActive: true, createdAt: '2026-10-01T00:00:00Z', updatedAt: null } }));
  });
  await page.route('**/api/inventory', route => route.fulfill({ status: 200, contentType: 'application/json', body: '[]' }));
  await page.goto('/inventory'); await expect(page.getByText('Stok kaydı açmak için bir ürün oluşturun.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'EN', exact: true }).click(); await expect(page.getByText('Create a product to initialize inventory.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'TR', exact: true }).click();
  await page.unroute('**/api/inventory');
  await page.route('**/api/inventory', route => route.fulfill({ status: 409, contentType: 'application/problem+json', body: JSON.stringify({ code: 'concurrentUpdate' }) }));
  await page.reload(); await expect(page.getByText('Eşzamanlı değişiklik çakışması. Yenileyip tekrar deneyin.', { exact: true })).toBeVisible();
});

test('product and category mutations refresh the cached inventory workspace', async ({ page }) => {
  const base = `${process.env.API_URL ?? 'http://localhost:5080'}/api`;
  const suffix = Date.now(); const email = `inventory-cache-${suffix}@example.com`; const password = 'InventoryCache123!';
  expect((await page.request.post(`${base}/auth/register`, { data: { name: 'Cache Reviewer', email, password } })).status()).toBe(201);
  await promoteRegistered(page.request, email);
  const session = await (await page.request.post(`${base}/auth/login`, { data: { email, password } })).json();
  const headers = { Authorization: `Bearer ${session.accessToken}` };
  const category = await (await page.request.post(`${base}/categories`, { headers, data: { name: `Cache category ${suffix}`, description: '', isActive: true } })).json();
  await page.goto('/auth/login'); await page.evaluate(value => sessionStorage.setItem('catalog.session', JSON.stringify(value)), session);
  await page.goto('/inventory'); await expect(page.getByRole('heading', { name: 'Inventory', exact: true })).toBeVisible();
  await page.goto('/products/new'); await page.getByLabel('Product name', { exact: false }).fill(`Cache product ${suffix}`);
  await page.getByLabel('Category', { exact: false }).selectOption(category.id); await page.getByLabel('Price (USD)').fill('10');
  await page.getByRole('button', { name: 'Create product', exact: true }).click();
  await expect(page.getByRole('heading', { name: `Cache product ${suffix}`, exact: true })).toBeVisible();
  const productId = page.url().split('/').at(-1)!;
  await page.getByRole('navigation').getByRole('link', { name: 'Inventory', exact: true }).click();
  await expect(page.getByText(`Cache product ${suffix}`, { exact: true }).filter({ visible: true })).toBeVisible();
  await page.goto(`/products/${productId}/edit`); await page.getByLabel('Product name', { exact: false }).fill(`Updated cache product ${suffix}`);
  await page.getByRole('button', { name: 'Save changes', exact: true }).click(); await expect(page.getByRole('heading', { name: `Updated cache product ${suffix}`, exact: true })).toBeVisible();
  await page.getByRole('navigation').getByRole('link', { name: 'Inventory', exact: true }).click();
  await expect(page.getByText(`Updated cache product ${suffix}`, { exact: true }).filter({ visible: true })).toBeVisible();
  await page.goto(`/categories/${category.id}/edit`); await page.getByLabel('Name', { exact: false }).fill(`Updated cache category ${suffix}`);
  await page.getByRole('button', { name: 'Save changes', exact: true }).click(); await expect(page.getByRole('heading', { name: `Updated cache category ${suffix}`, exact: true })).toBeVisible();
  await page.getByRole('navigation').getByRole('link', { name: 'Inventory', exact: true }).click();
  await expect(page.getByText(`Updated cache category ${suffix}`, { exact: true }).filter({ visible: true })).toBeVisible();
  await page.goto('/products'); const row = page.getByRole('row').filter({ hasText: `Updated cache product ${suffix}` });
  await row.getByRole('button', { name: `Delete Updated cache product ${suffix}`, exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Delete product', exact: true }).click(); await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('navigation').getByRole('link', { name: 'Inventory', exact: true }).click();
  await expect(page.getByText(`Updated cache product ${suffix}`, { exact: true }).filter({ visible: true })).toHaveCount(0);
});
