import { Can } from '../permissions';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useFieldArray, useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { api } from '../api';
import { t } from '../i18n';
import { dateFormat, ErrorNotice, FieldError, Loading, priceFormat, QueryError } from '../components';
import type { Customer, Product, Order, OrderSummary, OrderStatus, Inventory } from '../types';

function OrderBadge({ status }: { status: OrderStatus }) { return <span className={`badge order-${status.toLowerCase()}`}>{t(status)}</span>; }
export function OrderList() {
  const query = useQuery({ queryKey: ['orders'], queryFn: ({ signal }) => api<OrderSummary[]>('/orders', { signal }) });
  if (query.isPending) return <Loading />;
  if (query.isError) return <QueryError error={query.error} retry={() => void query.refetch()} back="/orders" />;
  return <><div className="page-heading"><div><p className="eyebrow">{t('YOUR WORKSPACE')}</p><h1>{t('Orders')}</h1><p>{t('Manage your business records.')}</p></div><Can permission="write"><Link className="button" to="/orders/new">＋ {t('New order')}</Link></Can></div>
    <div className="stats-grid order-stats">{[['Total orders', query.data.length], ['Pending orders', query.data.filter(o => o.status === 'Pending').length], ['Completed orders', query.data.filter(o => o.status === 'Completed').length], ['Total order value', priceFormat.format(query.data.filter(o => o.status !== 'Cancelled').reduce((total, o) => total + o.totalAmount, 0))]].map(([label, value]) => <div className="stat" key={label}><span>{t(String(label))}</span><strong className="stat-value">{value}</strong></div>)}</div>
    <section className="panel overflow-hidden p-0">{query.data.length === 0 ? <div className="p-10 text-center"><h2 className="text-xl font-semibold">{t('No records yet')}</h2><p className="mt-2 text-slate-500">{t('Create your first record to get started.')}</p></div> : <><div className="hidden overflow-x-auto md:block"><table><thead><tr>{['Order number', 'Customer', 'Order date', 'Status', 'Items', 'Total', 'Actions'].map(label => <th key={label}>{t(label)}</th>)}</tr></thead><tbody>{query.data.map(o => <tr key={o.id}><td><Link className="text-link whitespace-nowrap" to={`/orders/${o.id}`}>{o.orderNumber}</Link></td><td>{o.customerName}</td><td>{dateFormat(o.orderDate)}</td><td><OrderBadge status={o.status} /></td><td>{o.itemCount}</td><td className="whitespace-nowrap tabular-nums">{priceFormat.format(o.totalAmount)}</td><td><Link className="text-link" to={`/orders/${o.id}`}>{t('View')}</Link></td></tr>)}</tbody></table></div><ul className="divide-y divide-slate-100 md:hidden">{query.data.map(o => <li className="p-5" key={o.id}><div className="flex justify-between gap-2"><Link className="text-link break-all" to={`/orders/${o.id}`}>{o.orderNumber}</Link><OrderBadge status={o.status} /></div><p className="my-3 text-sm text-slate-500">{o.customerName} · {dateFormat(o.orderDate)}</p><div className="flex justify-between"><span>{t('Items')}: {o.itemCount}</span><strong>{priceFormat.format(o.totalAmount)}</strong></div></li>)}</ul></>}</section></>;
}
const schema = z.object({ customerId: z.string().min(1, 'Select a customer.'), items: z.array(z.object({ productId: z.string().min(1, 'Select a product.'), quantity: z.number({ error: 'Quantity must be a whole number greater than zero.' }).int('Quantity must be a whole number greater than zero.').min(1, 'Quantity must be a whole number greater than zero.').max(100000, 'Maximum length exceeded.') })).min(1, 'Add at least one item.').max(100, 'Maximum length exceeded.') }).refine(value => new Set(value.items.map(i => i.productId)).size === value.items.length, { path: ['items'], message: 'Choose each product only once.' });
type OrderInput = z.infer<typeof schema>;
export function OrderCreate() {
  const customers = useQuery({ queryKey: ['customers'], queryFn: ({ signal }) => api<Customer[]>('/customers', { signal }) });
  const products = useQuery({ queryKey: ['products'], queryFn: ({ signal }) => api<Product[]>('/products', { signal }) });
  const inventory = useQuery({ queryKey: ['inventory'], queryFn: ({ signal }) => api<Inventory[]>('/inventory', { signal }) });
  if (customers.isPending || products.isPending || inventory.isPending) return <Loading />;
  if (customers.isError || products.isError || inventory.isError) return <QueryError error={customers.error ?? products.error ?? inventory.error} retry={() => { void customers.refetch(); void products.refetch(); void inventory.refetch(); }} back="/orders" />;
  return <><Link className="back-link" to="/orders">← {t('Back to list')}</Link><div className="page-heading"><div><p className="eyebrow">{t('YOUR WORKSPACE')}</p><h1>{t('New order')}</h1><p>{t('Prices are calculated by the server when you submit.')}</p></div></div><OrderForm customers={customers.data.filter(c => c.isActive)} products={products.data.filter(p => p.isActive)} inventory={inventory.data} /></>;
}
function OrderForm({ customers, products, inventory }: { customers: Customer[]; products: Product[]; inventory: Inventory[] }) {
  const navigate = useNavigate(); const cache = useQueryClient();
  const { register, control, watch, handleSubmit, formState: { errors } } = useForm<OrderInput>({ resolver: zodResolver(schema), defaultValues: { customerId: '', items: [{ productId: '', quantity: 1 }] } });
  const { fields, append, remove } = useFieldArray({ control, name: 'items' });
  const lines = watch('items');
  const preview = lines.map(line => { const price = products.find(p => p.id === line.productId)?.price ?? 0; const quantity = Number.isFinite(line.quantity) && line.quantity > 0 ? line.quantity : 0; return { price, total: Math.round(price * quantity * 100) / 100 }; });
  const save = useMutation({ mutationFn: (input: OrderInput) => api<Order>('/orders', { method: 'POST', body: JSON.stringify(input) }), onSuccess: async result => { cache.setQueryData(['orders', result.id], result); await cache.invalidateQueries({ queryKey: ['orders'] }); await cache.invalidateQueries({ queryKey: ['customers'] }); navigate(`/orders/${result.id}`); } });
  return <form className="panel" noValidate onSubmit={handleSubmit(input => save.mutate(input))}><fieldset className="space-y-6" disabled={save.isPending}><ErrorNotice error={save.error} />{(!customers.length || !products.length) && <p className="notice">{t('Create an active customer and product first.')}</p>}
    <label className="field max-w-xl">{t('Customer')} *<select {...register('customerId')} aria-invalid={!!errors.customerId}><option value="">{t('Select a customer')}</option>{customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><FieldError message={errors.customerId?.message} /></label>
    <div className="flex items-center justify-between"><h2 className="font-semibold">{t('Items')}</h2><button className="button secondary" type="button" disabled={fields.length >= 100} onClick={() => append({ productId: '', quantity: 1 })}>＋ {t('Add item')}</button></div>
    {fields.map((field, index) => <div className="order-line" key={field.id}><label className="field">{t('Product name')} *<select {...register(`items.${index}.productId`)} aria-invalid={!!errors.items?.[index]?.productId}><option value="">{t('Select a product')}</option>{products.filter(p => p.id === lines[index]?.productId || !lines.some(line => line.productId === p.id)).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><FieldError message={errors.items?.[index]?.productId?.message} /></label><label className="field">{t('Quantity')} *<input type="number" min={1} max={100000} step={1} {...register(`items.${index}.quantity`, { valueAsNumber: true })} aria-invalid={!!errors.items?.[index]?.quantity} /><FieldError message={errors.items?.[index]?.quantity?.message} /></label><div><span className="text-xs text-slate-500">{t('Unit price')}</span><p className="mt-3 tabular-nums">{priceFormat.format(preview[index].price)}</p></div><div><span className="text-xs text-slate-500">{t('Line total')}</span><p className="mt-3 font-semibold tabular-nums">{priceFormat.format(preview[index].total)}</p></div><button type="button" className="text-sm text-red-700" onClick={() => remove(index)}>{t('Remove')}</button></div>)}
    <div className="space-y-3">{lines.filter(line => line.productId).map(line => { const available = inventory.find(i => i.productId === line.productId)?.quantityOnHand ?? 0; return <div className="rounded-lg bg-slate-50 p-4 text-sm" key={line.productId}><p><Link className="text-link" to={`/inventory/${line.productId}`}>{products.find(p => p.id === line.productId)?.name}</Link> · {t('Available stock')}: <strong>{available}</strong></p>{line.quantity > available && <p className="mt-2 text-amber-800" role="status">{t('Requested quantity exceeds current stock. Pending orders can still be created.')}</p>}</div>; })}</div>
    <FieldError message={errors.items?.message ?? errors.items?.root?.message} /><div className="order-total"><span>{t('Order total')}</span><strong>{priceFormat.format(preview.reduce((sum, line) => sum + line.total, 0))}</strong></div><div className="flex justify-end gap-3"><Link className="button secondary" to="/orders">{t('Cancel')}</Link><button className="button" disabled={save.isPending || !customers.length || !products.length}>{t(save.isPending ? 'Saving…' : 'Create order')}</button></div>
  </fieldset></form>;
}
export function OrderDetail() {
  const { id } = useParams(); const cache = useQueryClient();
  const query = useQuery({ queryKey: ['orders', id], queryFn: ({ signal }) => api<Order>(`/orders/${id}`, { signal }) });
  const status = useMutation({ mutationFn: (value: OrderStatus) => api<Order>(`/orders/${id}/status`, { method: 'PUT', body: JSON.stringify({ status: value }) }), onSuccess: async value => { cache.setQueryData(['orders', id], value); await Promise.all([cache.invalidateQueries({ queryKey: ['orders'] }), cache.invalidateQueries({ queryKey: ['inventory'] })]); }, onError: () => { void cache.invalidateQueries({ queryKey: ['inventory'] }); } });
  if (query.isPending) return <Loading />;
  if (query.isError) return <QueryError error={query.error} retry={() => void query.refetch()} back="/orders" />;
  const o = query.data;
  const impact = o.status === 'Pending' ? 'Confirmation checks and deducts stock atomically. Pending cancellation does not change stock.'
    : o.status === 'Confirmed' ? (o.inventoryWasDeducted ? 'Stock has been deducted. Completion makes no further deduction; cancellation returns the deducted stock.' : 'Historical order: no inventory deduction was recorded before inventory management was introduced.')
    : o.status === 'Completed' ? 'Completed orders cannot be cancelled.' : 'Cancelled orders cannot be reopened.';
  return <><Link className="back-link" to="/orders">← {t('Back to list')}</Link><div className="page-heading"><div><p className="eyebrow">{t('Order details')}</p><h1 className="break-all">{o.orderNumber}</h1><p>{dateFormat(o.orderDate)}</p></div><OrderBadge status={o.status} /></div><section className="panel"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 pb-6"><div><span className="text-xs text-slate-500">{t('Customer')}</span><p className="mt-1"><Link className="text-link" to={`/customers/${o.customerId}`}>{o.customerName}</Link></p></div><div className="flex flex-wrap gap-2"><Can permission="write">{(o.status === 'Pending' ? [['Confirmed', 'Confirm'], ['Cancelled', 'Cancel order']] : o.status === 'Confirmed' ? [['Completed', 'Complete'], ['Cancelled', 'Cancel order']] : []).map(([value, label]) => <button className={`button ${value === 'Cancelled' ? 'secondary' : ''}`} key={value} disabled={status.isPending} onClick={() => status.mutate(value as OrderStatus)}>{t(label)}</button>)}</Can></div></div><p className="notice mt-5">{t(impact)}</p><ErrorNotice error={status.error} />
    <div className="hidden overflow-x-auto md:block"><table><thead><tr>{['Product name', 'Quantity', 'Unit price', 'Line total'].map(label => <th key={label}>{t(label)}</th>)}</tr></thead><tbody>{o.items.map(line => <tr key={line.id}><td><Link className="text-link" to={`/products/${line.productId}`}>{line.productName}</Link></td><td>{line.quantity}</td><td className="whitespace-nowrap">{priceFormat.format(line.unitPrice)}</td><td className="whitespace-nowrap font-semibold">{priceFormat.format(line.lineTotal)}</td></tr>)}</tbody></table></div><ul className="divide-y divide-slate-100 md:hidden">{o.items.map(line => <li className="py-5" key={line.id}><Link className="text-link break-words" to={`/products/${line.productId}`}>{line.productName}</Link><p className="my-3 text-sm text-slate-500">{t('Quantity')}: {line.quantity}</p><div className="grid grid-cols-2 gap-4"><div><span className="text-xs text-slate-500">{t('Unit price')}</span><p className="mt-1 tabular-nums">{priceFormat.format(line.unitPrice)}</p></div><div><span className="text-xs text-slate-500">{t('Line total')}</span><p className="mt-1 font-semibold tabular-nums">{priceFormat.format(line.lineTotal)}</p></div></div></li>)}</ul><div className="order-total mt-6"><span>{t('Order total')}</span><strong>{priceFormat.format(o.totalAmount)}</strong></div></section></>;
}
